name: CI 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - name: Set up Python 
        uses: actions/setup-python@v5 
        with: 
          python-version: '3.11' 
      - name: Install dependencies 
        run: pip install -r requirements.txt 
      - name: Tests (pytest + coverage) 
        run: pytest --cov=app --cov-report=term-missing 
